# To be built
LOCAL_TARGET    =  
LOCAL_SOTARGET  = $(PROJECT_ROOT)/artefacts/lib/libsqlite-modern.so
LOCAL_OBJS      = sqlite3.o sqlite_modern_cpp.o

# Control.
LOCAL_LIBS      = 
LOCAL_LIBPATH   =
LOCAL_INCPATH   = 
LOCAL_DEFINES   =
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules
