# To be built
LOCAL_TARGET    = $(PROJECT_ROOT)/artefacts/bin/ccgen
LOCAL_SOTARGET  = 
LOCAL_OBJS      = ccgen.o

# Control.
LOCAL_LIBS      = -lboost_program_options -lboost_log -licuuc -licui18n -licudata
LOCAL_LIBPATH   = 
LOCAL_INCPATH   =
LOCAL_DEFINES   = -DBOOST_LOG_DYN_LINK -DASIO_STANDALONE -DBOOST_IOSTREAMS_NO_LIB
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =
  
include $(ENV_ROOT)/makerules/build.rules
