# To be built
LOCAL_TARGET    =
LOCAL_SOTARGET  = $(PROJECT_ROOT)/artefacts/lib/libccgen.so
LOCAL_OBJS      = Type.o Parameter.o Attribute.o Method.o Function.o \
	                CodeGen.o HeaderCodeGen.o Class.o Constructor.o Destructor.o StandardAssignOperator.o \
	                StandardConstructor.o TranslationUnit.o Headerfile.o StandardTranslationUnit.o \
	                Emitter.o

# Control.
LOCAL_LIBS      =
LOCAL_LIBPATH   = 
LOCAL_INCPATH   = 
LOCAL_DEFINES   =
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  = 
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =
  
include $(ENV_ROOT)/makerules/build.rules
